image: rocker/verse

stages:
  - checkPackage

before_script:
  - apt-get update
  - r -e 'install.packages(c("devtools", "roxygen2", "shiny", "shinyAce", "markdown"))'

documentation:
  stage: checkPackage
  script:
    - r -e 'devtools::document()'

check:
  stage: checkPackage
  script:
    - r -e 'devtools::build()'
    - cd ..
    - R CMD check --as-cran markdownInput_0.1.2.tar.gz

install:
  stage: checkPackage
  script:
    - r -e 'devtools::install()'
